### ISSUE TITLE
[ENHANCEMENT] Dark mode

### ISSUE THREAD

**Issue by mikejgray** [devvmh/ovos-web-client#1]
Love what you have so far. My one request that may not be on the immediate road map? Dark mode. :)

**Comment by devvmh** [comment]
Great idea! 

Leaving this link here for myself https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers

We can have a little settings widget that allows choosing explicitly, and the link above would detect an OS level preference

**Comment by devvmh** [comment]
@mikejgray do you have dark mode enabled in your OS settings, such that it'll be picked up by https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme?

**Comment by mikejgray** [comment]
> @mikejgray do you have dark mode enabled in your OS settings, such that it'll be picked up by https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme?

Sure do!

**Comment by mikejgray** [comment]
Looking good! Thank you!
<img width="1440" alt="image" src="https://github.com/devvmh/ovos-web-client/assets/30268971/3268383d-06d2-489a-b0d4-6cfc6619fd49">
